apiVersion: v1
kind: Service
metadata:
  name: app-cd
spec:
  type: LoadBalancer
  selector:
    app: cd
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
      name: app-cd
    spec:
      containers:
        - name: app-cd
          image: pas_a/app-cd
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8084